// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudDomainsV1
import GoogleLongRunning
import GoogleType
import GoogleWKT

func sample(client: DomainsClient, projectId: String, locationId: String, registrationId: String)
  async throws
{
  let poller = try await client.updateRegistrationPollingUntilDone(
    request: UpdateRegistrationRequest()
      .with {
        $0.registration = Registration().with {
          $0.name = "projects/\(projectId)/locations/\(locationId)/registrations/\(registrationId)"
        }
        $0.updateMask = GoogleWKT.WKTFieldMask(paths: ["field.path1", "field.path2"])
      }
  )
  let response = try await poller.wait()
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudDomainsV1.DomainsClient()
      try await sample(
        client: client, projectId: "[placeholder]", locationId: "[placeholder]",
        registrationId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
