// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for the `ConfigureContactSettings` method.
public struct ConfigureContactSettingsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the `Registration` whose contact settings are being updated,
  /// in the format `projects/*/locations/*/registrations/*`.
  public var registration: Swift.String = Swift.String()

  /// Fields of the `ContactSettings` to update.
  public var contactSettings: ContactSettings? = nil

  /// Required. The field mask describing which fields to update as a comma-separated list.
  /// For example, if only the registrant contact is being updated, the
  /// `update_mask` is `"registrant_contact"`.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// The list of contact notices that the caller acknowledges. The notices
  /// needed here depend on the values specified in `contact_settings`.
  public var contactNotices: [ContactNotice] = []

  /// Validate the request without actually updating the contact settings.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConfigureContactSettingsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigureContactSettingsRequest().with { $0.registration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let registration = CodingKeys(stringValue: "registration")
    static let contactSettings = CodingKeys(stringValue: "contactSettings")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let contactNotices = CodingKeys(stringValue: "contactNotices")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "registration",
      "contactSettings",
      "updateMask",
      "contactNotices",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .registration) {
      self.registration = value
    }
    self.contactSettings = try container.decodeIfPresent(
      ContactSettings.self, forKey: .contactSettings)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    if let value = try container.decodeIfPresent([ContactNotice].self, forKey: .contactNotices) {
      self.contactNotices = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.registration, forKey: .registration)
    try container.encodeIfPresent(self.contactSettings, forKey: .contactSettings)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encode(self.contactNotices, forKey: .contactNotices)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.ConfigureContactSettingsRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
