// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Defines a set of possible contact privacy settings for a `Registration`.
///
/// [ICANN](https://icann.org/) maintains the WHOIS database, a publicly
/// accessible mapping from domain name to contact information, and requires that
/// each domain name have an entry. Choose from these options to control how much
/// information in your `ContactSettings` is published.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ContactPrivacy: Codable, Equatable, Hashable, Sendable {
  /// The contact privacy settings are undefined.
  case unspecified
  /// All the data from `ContactSettings` is publicly available. When setting
  /// this option, you must also provide a
  /// `PUBLIC_CONTACT_DATA_ACKNOWLEDGEMENT` in the `contact_notices` field of the
  /// request.
  case publicContactData
  /// None of the data from `ContactSettings` is publicly available. Instead,
  /// proxy contact data is published for your domain. Email sent to the proxy
  /// email address is forwarded to the registrant's email address. Cloud Domains
  /// provides this privacy proxy service at no additional cost.
  case privateContactData
  /// Some data from `ContactSettings` is publicly available. The actual
  /// information redacted depends on the domain. For details, see [the
  /// registration privacy
  /// article](https://support.google.com/domains/answer/3251242).
  case redactedContactData
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .publicContactData: return 1
    case .privateContactData: return 2
    case .redactedContactData: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "CONTACT_PRIVACY_UNSPECIFIED"
    case .publicContactData: return "PUBLIC_CONTACT_DATA"
    case .privateContactData: return "PRIVATE_CONTACT_DATA"
    case .redactedContactData: return "REDACTED_CONTACT_DATA"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContactPrivacy/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CONTACT_PRIVACY_UNSPECIFIED": self = .unspecified
    case "PUBLIC_CONTACT_DATA": self = .publicContactData
    case "PRIVATE_CONTACT_DATA": self = .privateContactData
    case "REDACTED_CONTACT_DATA": self = .redactedContactData
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContactPrivacy/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .publicContactData
    case 2: self = .privateContactData
    case 3: self = .redactedContactData
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("CONTACT_PRIVACY_UNSPECIFIED")
    case .publicContactData: return try container.encode("PUBLIC_CONTACT_DATA")
    case .privateContactData: return try container.encode("PRIVATE_CONTACT_DATA")
    case .redactedContactData: return try container.encode("REDACTED_CONTACT_DATA")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
