// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines the contact information associated with a `Registration`.
///
/// [ICANN](https://icann.org/) requires all domain names to have associated
/// contact information. The `registrant_contact` is considered the
/// domain's legal owner, and often the other contacts are identical.
public struct ContactSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Privacy setting for the contacts associated with the `Registration`.
  public var privacy: ContactPrivacy = ContactPrivacy()

  /// Required. The registrant contact for the `Registration`.
  ///
  /// *Caution: Anyone with access to this email address, phone number,
  /// and/or postal address can take control of the domain.*
  ///
  /// *Warning: For new `Registration`s, the registrant receives an email
  /// confirmation that they must complete within 15 days to avoid domain
  /// suspension.*
  public var registrantContact: ContactSettings.Contact? = nil

  /// Required. The administrative contact for the `Registration`.
  public var adminContact: ContactSettings.Contact? = nil

  /// Required. The technical contact for the `Registration`.
  public var technicalContact: ContactSettings.Contact? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ContactSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContactSettings().with { $0.privacy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let privacy = CodingKeys(stringValue: "privacy")
    static let registrantContact = CodingKeys(stringValue: "registrantContact")
    static let adminContact = CodingKeys(stringValue: "adminContact")
    static let technicalContact = CodingKeys(stringValue: "technicalContact")

    static let _knownKeys: Set<Swift.String> = [
      "privacy",
      "registrantContact",
      "adminContact",
      "technicalContact",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(ContactPrivacy.self, forKey: .privacy) {
      self.privacy = value
    }
    self.registrantContact = try container.decodeIfPresent(
      ContactSettings.Contact.self, forKey: .registrantContact)
    self.adminContact = try container.decodeIfPresent(
      ContactSettings.Contact.self, forKey: .adminContact)
    self.technicalContact = try container.decodeIfPresent(
      ContactSettings.Contact.self, forKey: .technicalContact)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.privacy, forKey: .privacy)
    try container.encodeIfPresent(self.registrantContact, forKey: .registrantContact)
    try container.encodeIfPresent(self.adminContact, forKey: .adminContact)
    try container.encodeIfPresent(self.technicalContact, forKey: .technicalContact)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details required for a contact associated with a `Registration`.
  public struct Contact: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Postal address of the contact.
    public var postalAddress: GoogleType.PostalAddress? = nil

    /// Required. Email address of the contact.
    public var email: Swift.String = Swift.String()

    /// Required. Phone number of the contact in international format. For example,
    /// `"+1-800-555-0123"`.
    public var phoneNumber: Swift.String = Swift.String()

    /// Fax number of the contact in international format. For example,
    /// `"+1-800-555-0123"`.
    public var faxNumber: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Contact`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Contact().with { $0.postalAddress = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let postalAddress = CodingKeys(stringValue: "postalAddress")
      static let email = CodingKeys(stringValue: "email")
      static let phoneNumber = CodingKeys(stringValue: "phoneNumber")
      static let faxNumber = CodingKeys(stringValue: "faxNumber")

      static let _knownKeys: Set<Swift.String> = [
        "postalAddress",
        "email",
        "phoneNumber",
        "faxNumber",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.postalAddress = try container.decodeIfPresent(
        GoogleType.PostalAddress.self, forKey: .postalAddress)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .email) {
        self.email = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .phoneNumber) {
        self.phoneNumber = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .faxNumber) {
        self.faxNumber = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.postalAddress, forKey: .postalAddress)
      try container.encode(self.email, forKey: .email)
      try container.encode(self.phoneNumber, forKey: .phoneNumber)
      try container.encode(self.faxNumber, forKey: .faxNumber)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.domains.v1.ContactSettings.Contact"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.ContactSettings"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
