// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines the DNS configuration of a `Registration`, including name servers,
/// DNSSEC, and glue records.
public struct DnsSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of glue records for this `Registration`. Commonly empty.
  public var glueRecords: [DnsSettings.GlueRecord] = []

  /// The DNS provider of the registration.
  public var dnsProvider: OneOf_DnsProvider? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DnsSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DnsSettings().with { $0.customDns = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let customDns = CodingKeys(stringValue: "customDns")
    static let googleDomainsDns = CodingKeys(stringValue: "googleDomainsDns")
    static let glueRecords = CodingKeys(stringValue: "glueRecords")

    static let _knownKeys: Set<Swift.String> = [
      "customDns",
      "googleDomainsDns",
      "glueRecords",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [DnsSettings.GlueRecord].self, forKey: .glueRecords)
    {
      self.glueRecords = value
    }

    var dnsProvider: OneOf_DnsProvider? = nil
    let dnsProviderCheckAndSet = {
      if dnsProvider != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dnsProvider'"))
      }
      dnsProvider = $0
    }
    if let customDns = try container.decodeIfPresent(
      DnsSettings.CustomDns?.self, forKey: .customDns)
    {
      try dnsProviderCheckAndSet(.customDns(customDns))
    }
    if let googleDomainsDns = try container.decodeIfPresent(
      DnsSettings.GoogleDomainsDns?.self, forKey: .googleDomainsDns)
    {
      try dnsProviderCheckAndSet(.googleDomainsDns(googleDomainsDns))
    }
    self.dnsProvider = dnsProvider
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.glueRecords, forKey: .glueRecords)

    if let choice = self.dnsProvider {
      switch choice {
      case .customDns(let value):
        try container.encode(value, forKey: .customDns)
      case .googleDomainsDns(let value):
        try container.encode(value, forKey: .googleDomainsDns)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for an arbitrary DNS provider.
  public struct CustomDns: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. A list of name servers that store the DNS zone for this domain. Each name
    /// server is a domain name, with Unicode domain names expressed in
    /// Punycode format.
    public var nameServers: [Swift.String] = []

    /// The list of DS records for this domain, which are used to enable DNSSEC.
    /// The domain's DNS provider can provide the values to set here. If this
    /// field is empty, DNSSEC is disabled.
    public var dsRecords: [DnsSettings.DsRecord] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CustomDns`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomDns().with { $0.nameServers = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nameServers = CodingKeys(stringValue: "nameServers")
      static let dsRecords = CodingKeys(stringValue: "dsRecords")

      static let _knownKeys: Set<Swift.String> = [
        "nameServers",
        "dsRecords",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .nameServers) {
        self.nameServers = value
      }
      if let value = try container.decodeIfPresent([DnsSettings.DsRecord].self, forKey: .dsRecords)
      {
        self.dsRecords = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nameServers, forKey: .nameServers)
      try container.encode(self.dsRecords, forKey: .dsRecords)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.domains.v1.DnsSettings.CustomDns"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for using the free DNS zone provided by Google Domains as a
  /// `Registration`'s `dns_provider`. You cannot configure the DNS zone itself
  /// using the API. To configure the DNS zone, go to
  /// [Google Domains](https://domains.google/).
  public struct GoogleDomainsDns: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. A list of name servers that store the DNS zone for this domain. Each name
    /// server is a domain name, with Unicode domain names expressed in
    /// Punycode format. This field is automatically populated with the name
    /// servers assigned to the Google Domains DNS zone.
    public var nameServers: [Swift.String] = []

    /// Required. The state of DS records for this domain. Used to enable or disable
    /// automatic DNSSEC.
    public var dsState: DnsSettings.DsState = DnsSettings.DsState()

    /// Output only. The list of DS records published for this domain. The list is
    /// automatically populated when `ds_state` is `DS_RECORDS_PUBLISHED`,
    /// otherwise it remains empty.
    public var dsRecords: [DnsSettings.DsRecord] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GoogleDomainsDns`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GoogleDomainsDns().with { $0.nameServers = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nameServers = CodingKeys(stringValue: "nameServers")
      static let dsState = CodingKeys(stringValue: "dsState")
      static let dsRecords = CodingKeys(stringValue: "dsRecords")

      static let _knownKeys: Set<Swift.String> = [
        "nameServers",
        "dsState",
        "dsRecords",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .nameServers) {
        self.nameServers = value
      }
      if let value = try container.decodeIfPresent(DnsSettings.DsState.self, forKey: .dsState) {
        self.dsState = value
      }
      if let value = try container.decodeIfPresent([DnsSettings.DsRecord].self, forKey: .dsRecords)
      {
        self.dsRecords = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nameServers, forKey: .nameServers)
      try container.encode(self.dsState, forKey: .dsState)
      try container.encode(self.dsRecords, forKey: .dsRecords)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.domains.v1.DnsSettings.GoogleDomainsDns"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines a Delegation Signer (DS) record, which is needed to enable DNSSEC
  /// for a domain. It contains a digest (hash) of a DNSKEY record that must be
  /// present in the domain's DNS zone.
  public struct DsRecord: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The key tag of the record. Must be set in range 0 -- 65535.
    public var keyTag: Swift.Int32 = Swift.Int32()

    /// The algorithm used to generate the referenced DNSKEY.
    public var algorithm: DnsSettings.DsRecord.Algorithm = DnsSettings.DsRecord.Algorithm()

    /// The hash function used to generate the digest of the referenced DNSKEY.
    public var digestType: DnsSettings.DsRecord.DigestType = DnsSettings.DsRecord.DigestType()

    /// The digest generated from the referenced DNSKEY.
    public var digest: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DsRecord`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DsRecord().with { $0.keyTag = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let keyTag = CodingKeys(stringValue: "keyTag")
      static let algorithm = CodingKeys(stringValue: "algorithm")
      static let digestType = CodingKeys(stringValue: "digestType")
      static let digest = CodingKeys(stringValue: "digest")

      static let _knownKeys: Set<Swift.String> = [
        "keyTag",
        "algorithm",
        "digestType",
        "digest",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .keyTag) {
        self.keyTag = value
      }
      if let value = try container.decodeIfPresent(
        DnsSettings.DsRecord.Algorithm.self, forKey: .algorithm)
      {
        self.algorithm = value
      }
      if let value = try container.decodeIfPresent(
        DnsSettings.DsRecord.DigestType.self, forKey: .digestType)
      {
        self.digestType = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .digest) {
        self.digest = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.keyTag, forKey: .keyTag)
      try container.encode(self.algorithm, forKey: .algorithm)
      try container.encode(self.digestType, forKey: .digestType)
      try container.encode(self.digest, forKey: .digest)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// List of algorithms used to create a DNSKEY. Certain
    /// algorithms are not supported for particular domains.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Algorithm: Codable, Equatable, Sendable {
      /// The algorithm is unspecified.
      case unspecified
      /// RSA/MD5. Cannot be used for new deployments.
      case rsamd5
      /// Diffie-Hellman. Cannot be used for new deployments.
      case dh
      /// DSA/SHA1. Not recommended for new deployments.
      case dsa
      /// ECC. Not recommended for new deployments.
      case ecc
      /// RSA/SHA-1. Not recommended for new deployments.
      case rsasha1
      /// DSA-NSEC3-SHA1. Not recommended for new deployments.
      case dsansec3Sha1
      /// RSA/SHA1-NSEC3-SHA1. Not recommended for new deployments.
      case rsasha1Nsec3Sha1
      /// RSA/SHA-256.
      case rsasha256
      /// RSA/SHA-512.
      case rsasha512
      /// GOST R 34.10-2001.
      case eccgost
      /// ECDSA Curve P-256 with SHA-256.
      case ecdsap256Sha256
      /// ECDSA Curve P-384 with SHA-384.
      case ecdsap384Sha384
      /// Ed25519.
      case ed25519
      /// Ed448.
      case ed448
      /// Reserved for Indirect Keys. Cannot be used for new deployments.
      case `indirect`
      /// Private algorithm. Cannot be used for new deployments.
      case privatedns
      /// Private algorithm OID. Cannot be used for new deployments.
      case privateoid
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .rsamd5: return 1
        case .dh: return 2
        case .dsa: return 3
        case .ecc: return 4
        case .rsasha1: return 5
        case .dsansec3Sha1: return 6
        case .rsasha1Nsec3Sha1: return 7
        case .rsasha256: return 8
        case .rsasha512: return 10
        case .eccgost: return 12
        case .ecdsap256Sha256: return 13
        case .ecdsap384Sha384: return 14
        case .ed25519: return 15
        case .ed448: return 16
        case .`indirect`: return 252
        case .privatedns: return 253
        case .privateoid: return 254
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ALGORITHM_UNSPECIFIED"
        case .rsamd5: return "RSAMD5"
        case .dh: return "DH"
        case .dsa: return "DSA"
        case .ecc: return "ECC"
        case .rsasha1: return "RSASHA1"
        case .dsansec3Sha1: return "DSANSEC3SHA1"
        case .rsasha1Nsec3Sha1: return "RSASHA1NSEC3SHA1"
        case .rsasha256: return "RSASHA256"
        case .rsasha512: return "RSASHA512"
        case .eccgost: return "ECCGOST"
        case .ecdsap256Sha256: return "ECDSAP256SHA256"
        case .ecdsap384Sha384: return "ECDSAP384SHA384"
        case .ed25519: return "ED25519"
        case .ed448: return "ED448"
        case .`indirect`: return "INDIRECT"
        case .privatedns: return "PRIVATEDNS"
        case .privateoid: return "PRIVATEOID"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Algorithm/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ALGORITHM_UNSPECIFIED": self = .unspecified
        case "RSAMD5": self = .rsamd5
        case "DH": self = .dh
        case "DSA": self = .dsa
        case "ECC": self = .ecc
        case "RSASHA1": self = .rsasha1
        case "DSANSEC3SHA1": self = .dsansec3Sha1
        case "RSASHA1NSEC3SHA1": self = .rsasha1Nsec3Sha1
        case "RSASHA256": self = .rsasha256
        case "RSASHA512": self = .rsasha512
        case "ECCGOST": self = .eccgost
        case "ECDSAP256SHA256": self = .ecdsap256Sha256
        case "ECDSAP384SHA384": self = .ecdsap384Sha384
        case "ED25519": self = .ed25519
        case "ED448": self = .ed448
        case "INDIRECT": self = .`indirect`
        case "PRIVATEDNS": self = .privatedns
        case "PRIVATEOID": self = .privateoid
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Algorithm/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .rsamd5
        case 2: self = .dh
        case 3: self = .dsa
        case 4: self = .ecc
        case 5: self = .rsasha1
        case 6: self = .dsansec3Sha1
        case 7: self = .rsasha1Nsec3Sha1
        case 8: self = .rsasha256
        case 10: self = .rsasha512
        case 12: self = .eccgost
        case 13: self = .ecdsap256Sha256
        case 14: self = .ecdsap384Sha384
        case 15: self = .ed25519
        case 16: self = .ed448
        case 252: self = .`indirect`
        case 253: self = .privatedns
        case 254: self = .privateoid
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("ALGORITHM_UNSPECIFIED")
        case .rsamd5: return try container.encode("RSAMD5")
        case .dh: return try container.encode("DH")
        case .dsa: return try container.encode("DSA")
        case .ecc: return try container.encode("ECC")
        case .rsasha1: return try container.encode("RSASHA1")
        case .dsansec3Sha1: return try container.encode("DSANSEC3SHA1")
        case .rsasha1Nsec3Sha1: return try container.encode("RSASHA1NSEC3SHA1")
        case .rsasha256: return try container.encode("RSASHA256")
        case .rsasha512: return try container.encode("RSASHA512")
        case .eccgost: return try container.encode("ECCGOST")
        case .ecdsap256Sha256: return try container.encode("ECDSAP256SHA256")
        case .ecdsap384Sha384: return try container.encode("ECDSAP384SHA384")
        case .ed25519: return try container.encode("ED25519")
        case .ed448: return try container.encode("ED448")
        case .`indirect`: return try container.encode("INDIRECT")
        case .privatedns: return try container.encode("PRIVATEDNS")
        case .privateoid: return try container.encode("PRIVATEOID")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// List of hash functions that may have been used to generate a digest of a
    /// DNSKEY.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum DigestType: Codable, Equatable, Sendable {
      /// The DigestType is unspecified.
      case unspecified
      /// SHA-1. Not recommended for new deployments.
      case sha1
      /// SHA-256.
      case sha256
      /// GOST R 34.11-94.
      case gost3411
      /// SHA-384.
      case sha384
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .sha1: return 1
        case .sha256: return 2
        case .gost3411: return 3
        case .sha384: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DIGEST_TYPE_UNSPECIFIED"
        case .sha1: return "SHA1"
        case .sha256: return "SHA256"
        case .gost3411: return "GOST3411"
        case .sha384: return "SHA384"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DigestType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DIGEST_TYPE_UNSPECIFIED": self = .unspecified
        case "SHA1": self = .sha1
        case "SHA256": self = .sha256
        case "GOST3411": self = .gost3411
        case "SHA384": self = .sha384
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DigestType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .sha1
        case 2: self = .sha256
        case 3: self = .gost3411
        case 4: self = .sha384
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("DIGEST_TYPE_UNSPECIFIED")
        case .sha1: return try container.encode("SHA1")
        case .sha256: return try container.encode("SHA256")
        case .gost3411: return try container.encode("GOST3411")
        case .sha384: return try container.encode("SHA384")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.domains.v1.DnsSettings.DsRecord"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines a host on your domain that is a DNS name server for your domain
  /// and/or other domains. Glue records are a way of making the IP address of a
  /// name server known, even when it serves DNS queries for its parent domain.
  /// For example, when `ns.example.com` is a name server for `example.com`, the
  /// host `ns.example.com` must have a glue record to break the circular DNS
  /// reference.
  public struct GlueRecord: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Domain name of the host in Punycode format.
    public var hostName: Swift.String = Swift.String()

    /// List of IPv4 addresses corresponding to this host in the standard decimal
    /// format (e.g. `198.51.100.1`). At least one of `ipv4_address` and
    /// `ipv6_address` must be set.
    public var ipv4Addresses: [Swift.String] = []

    /// List of IPv6 addresses corresponding to this host in the standard
    /// hexadecimal format (e.g. `2001:db8::`). At least one of
    /// `ipv4_address` and `ipv6_address` must be set.
    public var ipv6Addresses: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GlueRecord`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GlueRecord().with { $0.hostName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let hostName = CodingKeys(stringValue: "hostName")
      static let ipv4Addresses = CodingKeys(stringValue: "ipv4Addresses")
      static let ipv6Addresses = CodingKeys(stringValue: "ipv6Addresses")

      static let _knownKeys: Set<Swift.String> = [
        "hostName",
        "ipv4Addresses",
        "ipv6Addresses",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostName) {
        self.hostName = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipv4Addresses) {
        self.ipv4Addresses = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipv6Addresses) {
        self.ipv6Addresses = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.hostName, forKey: .hostName)
      try container.encode(self.ipv4Addresses, forKey: .ipv4Addresses)
      try container.encode(self.ipv6Addresses, forKey: .ipv6Addresses)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.domains.v1.DnsSettings.GlueRecord"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The publication state of DS records for a `Registration`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DsState: Codable, Equatable, Sendable {
    /// DS state is unspecified.
    case unspecified
    /// DNSSEC is disabled for this domain. No DS records for this domain are
    /// published in the parent DNS zone.
    case dsRecordsUnpublished
    /// DNSSEC is enabled for this domain. Appropriate DS records for this domain
    /// are published in the parent DNS zone. This option is valid only if the
    /// DNS zone referenced in the `Registration`'s `dns_provider` field is
    /// already DNSSEC-signed.
    case dsRecordsPublished
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dsRecordsUnpublished: return 1
      case .dsRecordsPublished: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DS_STATE_UNSPECIFIED"
      case .dsRecordsUnpublished: return "DS_RECORDS_UNPUBLISHED"
      case .dsRecordsPublished: return "DS_RECORDS_PUBLISHED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DsState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DS_STATE_UNSPECIFIED": self = .unspecified
      case "DS_RECORDS_UNPUBLISHED": self = .dsRecordsUnpublished
      case "DS_RECORDS_PUBLISHED": self = .dsRecordsPublished
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DsState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dsRecordsUnpublished
      case 2: self = .dsRecordsPublished
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DS_STATE_UNSPECIFIED")
      case .dsRecordsUnpublished: return try container.encode("DS_RECORDS_UNPUBLISHED")
      case .dsRecordsPublished: return try container.encode("DS_RECORDS_PUBLISHED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The DNS provider of the registration.
  public enum OneOf_DnsProvider: Codable, Equatable, Sendable {
    /// An arbitrary DNS provider identified by its name servers.
    indirect case customDns(DnsSettings.CustomDns?)
    /// The free DNS zone provided by
    /// [Google Domains](https://domains.google/).
    indirect case googleDomainsDns(DnsSettings.GoogleDomainsDns?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.DnsSettings"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
