// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The Cloud Domains API enables management and configuration of domain names.
///
/// @Snippet(path: "DomainsQuickstart")
public final class DomainsClient: Clients.DomainsProtocol, Sendable {
  let inner: any Clients.DomainsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `DomainsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DomainsStub = try Clients.DomainsTransport(options)
    inner = Clients.DomainsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DomainsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Searches for available domain names similar to the provided query.
  ///
  /// Availability results from this method are approximate; call
  /// `RetrieveRegisterParameters` on a domain before registering to confirm
  /// availability.
  ///
  /// @Snippet(path: "Domains_SearchDomains")
  public func searchDomains(
    request: SearchDomainsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.SearchDomainsResponse {
    try await self.inner.searchDomains(request: request, options: options)
  }

  /// Gets parameters needed to register a new domain name, including price and
  /// up-to-date availability. Use the returned values to call `RegisterDomain`.
  ///
  /// @Snippet(path: "Domains_RetrieveRegisterParameters")
  public func retrieveRegisterParameters(
    request: RetrieveRegisterParametersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse {
    try await self.inner.retrieveRegisterParameters(request: request, options: options)
  }

  /// Registers a new domain name and creates a corresponding `Registration`
  /// resource.
  ///
  /// Call `RetrieveRegisterParameters` first to check availability of the domain
  /// name and determine parameters like price that are needed to build a call to
  /// this method.
  ///
  /// A successful call creates a `Registration` resource in state
  /// `REGISTRATION_PENDING`, which resolves to `ACTIVE` within 1-2
  /// minutes, indicating that the domain was successfully registered. If the
  /// resource ends up in state `REGISTRATION_FAILED`, it indicates that the
  /// domain was not registered successfully, and you can safely delete the
  /// resource and retry registration.
  ///
  /// @Snippet(path: "Domains_RegisterDomain")
  public func registerDomain(
    request: RegisterDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.registerDomain(request: request, options: options)
  }

  /// Registers a new domain name and creates a corresponding `Registration`
  /// resource.
  ///
  /// Call `RetrieveRegisterParameters` first to check availability of the domain
  /// name and determine parameters like price that are needed to build a call to
  /// this method.
  ///
  /// A successful call creates a `Registration` resource in state
  /// `REGISTRATION_PENDING`, which resolves to `ACTIVE` within 1-2
  /// minutes, indicating that the domain was successfully registered. If the
  /// resource ends up in state `REGISTRATION_FAILED`, it indicates that the
  /// domain was not registered successfully, and you can safely delete the
  /// resource and retry registration.
  ///
  /// @Snippet(path: "Domains_RegisterDomain")
  public func registerDomainPollingUntilDone(
    request: RegisterDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.registerDomain(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets parameters needed to transfer a domain name from another registrar to
  /// Cloud Domains. For domains managed by Google Domains, transferring to Cloud
  /// Domains is not supported.
  ///
  ///
  /// Use the returned values to call `TransferDomain`.
  ///
  /// @Snippet(path: "Domains_RetrieveTransferParameters")
  public func retrieveTransferParameters(
    request: RetrieveTransferParametersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse {
    try await self.inner.retrieveTransferParameters(request: request, options: options)
  }

  /// Transfers a domain name from another registrar to Cloud Domains.  For
  /// domains managed by Google Domains, transferring to Cloud Domains is not
  /// supported.
  ///
  ///
  /// Before calling this method, go to the domain's current registrar to unlock
  /// the domain for transfer and retrieve the domain's transfer authorization
  /// code. Then call `RetrieveTransferParameters` to confirm that the domain is
  /// unlocked and to get values needed to build a call to this method.
  ///
  /// A successful call creates a `Registration` resource in state
  /// `TRANSFER_PENDING`. It can take several days to complete the transfer
  /// process. The registrant can often speed up this process by approving the
  /// transfer through the current registrar, either by clicking a link in an
  /// email from the registrar or by visiting the registrar's website.
  ///
  /// A few minutes after transfer approval, the resource transitions to state
  /// `ACTIVE`, indicating that the transfer was successful. If the transfer is
  /// rejected or the request expires without being approved, the resource can
  /// end up in state `TRANSFER_FAILED`. If transfer fails, you can safely delete
  /// the resource and retry the transfer.
  ///
  /// @Snippet(path: "Domains_TransferDomain")
  public func transferDomain(
    request: TransferDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.transferDomain(request: request, options: options)
  }

  /// Transfers a domain name from another registrar to Cloud Domains.  For
  /// domains managed by Google Domains, transferring to Cloud Domains is not
  /// supported.
  ///
  ///
  /// Before calling this method, go to the domain's current registrar to unlock
  /// the domain for transfer and retrieve the domain's transfer authorization
  /// code. Then call `RetrieveTransferParameters` to confirm that the domain is
  /// unlocked and to get values needed to build a call to this method.
  ///
  /// A successful call creates a `Registration` resource in state
  /// `TRANSFER_PENDING`. It can take several days to complete the transfer
  /// process. The registrant can often speed up this process by approving the
  /// transfer through the current registrar, either by clicking a link in an
  /// email from the registrar or by visiting the registrar's website.
  ///
  /// A few minutes after transfer approval, the resource transitions to state
  /// `ACTIVE`, indicating that the transfer was successful. If the transfer is
  /// rejected or the request expires without being approved, the resource can
  /// end up in state `TRANSFER_FAILED`. If transfer fails, you can safely delete
  /// the resource and retry the transfer.
  ///
  /// @Snippet(path: "Domains_TransferDomain")
  public func transferDomainPollingUntilDone(
    request: TransferDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.transferDomain(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the `Registration` resources in a project.
  ///
  /// @Snippet(path: "Domains_ListRegistrations")
  public func listRegistrations(
    request: ListRegistrationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.ListRegistrationsResponse {
    try await self.inner.listRegistrations(request: request, options: options)
  }

  /// Gets the details of a `Registration` resource.
  ///
  /// @Snippet(path: "Domains_GetRegistration")
  public func getRegistration(
    request: GetRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.Registration {
    try await self.inner.getRegistration(request: request, options: options)
  }

  /// Updates select fields of a `Registration` resource, notably `labels`. To
  /// update other fields, use the appropriate custom update method:
  ///
  /// * To update management settings, see `ConfigureManagementSettings`
  /// * To update DNS configuration, see `ConfigureDnsSettings`
  /// * To update contact information, see `ConfigureContactSettings`
  ///
  /// @Snippet(path: "Domains_UpdateRegistration")
  public func updateRegistration(
    request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateRegistration(request: request, options: options)
  }

  /// Updates select fields of a `Registration` resource, notably `labels`. To
  /// update other fields, use the appropriate custom update method:
  ///
  /// * To update management settings, see `ConfigureManagementSettings`
  /// * To update DNS configuration, see `ConfigureDnsSettings`
  /// * To update contact information, see `ConfigureContactSettings`
  ///
  /// @Snippet(path: "Domains_UpdateRegistration")
  public func updateRegistrationPollingUntilDone(
    request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.updateRegistration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a `Registration`'s management settings.
  ///
  /// @Snippet(path: "Domains_ConfigureManagementSettings")
  public func configureManagementSettings(
    request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.configureManagementSettings(request: request, options: options)
  }

  /// Updates a `Registration`'s management settings.
  ///
  /// @Snippet(path: "Domains_ConfigureManagementSettings")
  public func configureManagementSettingsPollingUntilDone(
    request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.configureManagementSettings(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a `Registration`'s DNS settings.
  ///
  /// @Snippet(path: "Domains_ConfigureDnsSettings")
  public func configureDnsSettings(
    request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.configureDnsSettings(request: request, options: options)
  }

  /// Updates a `Registration`'s DNS settings.
  ///
  /// @Snippet(path: "Domains_ConfigureDnsSettings")
  public func configureDnsSettingsPollingUntilDone(
    request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.configureDnsSettings(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a `Registration`'s contact settings. Some changes require
  /// confirmation by the domain's registrant contact .
  ///
  /// @Snippet(path: "Domains_ConfigureContactSettings")
  public func configureContactSettings(
    request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.configureContactSettings(request: request, options: options)
  }

  /// Updates a `Registration`'s contact settings. Some changes require
  /// confirmation by the domain's registrant contact .
  ///
  /// @Snippet(path: "Domains_ConfigureContactSettings")
  public func configureContactSettingsPollingUntilDone(
    request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.configureContactSettings(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Exports a `Registration` resource, such that it is no longer managed by
  /// Cloud Domains.
  ///
  /// When an active domain is successfully exported, you can continue to use the
  /// domain in [Google Domains](https://domains.google/) until it expires. The
  /// calling user becomes the domain's sole owner in Google Domains, and
  /// permissions for the domain are subsequently managed there. The domain does
  /// not renew automatically unless the new owner sets up billing in Google
  /// Domains.
  ///
  /// @Snippet(path: "Domains_ExportRegistration")
  public func exportRegistration(
    request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportRegistration(request: request, options: options)
  }

  /// Exports a `Registration` resource, such that it is no longer managed by
  /// Cloud Domains.
  ///
  /// When an active domain is successfully exported, you can continue to use the
  /// domain in [Google Domains](https://domains.google/) until it expires. The
  /// calling user becomes the domain's sole owner in Google Domains, and
  /// permissions for the domain are subsequently managed there. The domain does
  /// not renew automatically unless the new owner sets up billing in Google
  /// Domains.
  ///
  /// @Snippet(path: "Domains_ExportRegistration")
  public func exportRegistrationPollingUntilDone(
    request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Registration>.State in
      return try op._extractStatus(Registration.self)
    }
    let rawOp = try await self.exportRegistration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a `Registration` resource.
  ///
  /// This method works on any `Registration` resource using [Subscription or
  /// Commitment billing](/domains/pricing#billing-models), provided that the
  /// resource was created at least 1 day in the past.
  ///
  /// For `Registration` resources using
  /// [Monthly billing](/domains/pricing#billing-models), this method works if:
  ///
  /// * `state` is `EXPORTED` with `expire_time` in the past
  /// * `state` is `REGISTRATION_FAILED`
  /// * `state` is `TRANSFER_FAILED`
  ///
  /// When an active registration is successfully deleted, you can continue to
  /// use the domain in [Google Domains](https://domains.google/) until it
  /// expires. The calling user becomes the domain's sole owner in Google
  /// Domains, and permissions for the domain are subsequently managed there. The
  /// domain does not renew automatically unless the new owner sets up billing in
  /// Google Domains.
  ///
  /// @Snippet(path: "Domains_DeleteRegistration")
  public func deleteRegistration(
    request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteRegistration(request: request, options: options)
  }

  /// Deletes a `Registration` resource.
  ///
  /// This method works on any `Registration` resource using [Subscription or
  /// Commitment billing](/domains/pricing#billing-models), provided that the
  /// resource was created at least 1 day in the past.
  ///
  /// For `Registration` resources using
  /// [Monthly billing](/domains/pricing#billing-models), this method works if:
  ///
  /// * `state` is `EXPORTED` with `expire_time` in the past
  /// * `state` is `REGISTRATION_FAILED`
  /// * `state` is `TRANSFER_FAILED`
  ///
  /// When an active registration is successfully deleted, you can continue to
  /// use the domain in [Google Domains](https://domains.google/) until it
  /// expires. The calling user becomes the domain's sole owner in Google
  /// Domains, and permissions for the domain are subsequently managed there. The
  /// domain does not renew automatically unless the new owner sets up billing in
  /// Google Domains.
  ///
  /// @Snippet(path: "Domains_DeleteRegistration")
  public func deleteRegistrationPollingUntilDone(
    request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteRegistration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the authorization code of the `Registration` for the purpose of
  /// transferring the domain to another registrar.
  ///
  /// You can call this method only after 60 days have elapsed since the initial
  /// domain registration.
  ///
  /// @Snippet(path: "Domains_RetrieveAuthorizationCode")
  public func retrieveAuthorizationCode(
    request: RetrieveAuthorizationCodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
    try await self.inner.retrieveAuthorizationCode(request: request, options: options)
  }

  /// Resets the authorization code of the `Registration` to a new random string.
  ///
  /// You can call this method only after 60 days have elapsed since the initial
  /// domain registration.
  ///
  /// @Snippet(path: "Domains_ResetAuthorizationCode")
  public func resetAuthorizationCode(
    request: ResetAuthorizationCodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
    try await self.inner.resetAuthorizationCode(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Domains_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Domains_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DomainsClient`.
  ///
  /// To mock `DomainsClient` change your functions to receive
  /// `some DomainsProtocol` or `any DomainsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DomainsProtocol: Sendable {
    /// See `DomainsClient.searchDomains`.
    func searchDomains(
      request: SearchDomainsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.SearchDomainsResponse

    /// See `DomainsClient.retrieveRegisterParameters`.
    func retrieveRegisterParameters(
      request: RetrieveRegisterParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse

    /// See `DomainsClient.registerDomain`.
    func registerDomain(
      request: RegisterDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.registerDomain`.
    func registerDomainPollingUntilDone(
      request: RegisterDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.retrieveTransferParameters`.
    func retrieveTransferParameters(
      request: RetrieveTransferParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse

    /// See `DomainsClient.transferDomain`.
    func transferDomain(
      request: TransferDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.transferDomain`.
    func transferDomainPollingUntilDone(
      request: TransferDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.listRegistrations`.
    func listRegistrations(
      request: ListRegistrationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.ListRegistrationsResponse

    /// See `DomainsClient.getRegistration`.
    func getRegistration(
      request: GetRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.Registration

    /// See `DomainsClient.updateRegistration`.
    func updateRegistration(
      request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.updateRegistration`.
    func updateRegistrationPollingUntilDone(
      request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.configureManagementSettings`.
    func configureManagementSettings(
      request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.configureManagementSettings`.
    func configureManagementSettingsPollingUntilDone(
      request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.configureDnsSettings`.
    func configureDnsSettings(
      request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.configureDnsSettings`.
    func configureDnsSettingsPollingUntilDone(
      request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.configureContactSettings`.
    func configureContactSettings(
      request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.configureContactSettings`.
    func configureContactSettingsPollingUntilDone(
      request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.exportRegistration`.
    func exportRegistration(
      request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.exportRegistration`.
    func exportRegistrationPollingUntilDone(
      request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Registration>

    /// See `DomainsClient.deleteRegistration`.
    func deleteRegistration(
      request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DomainsClient.deleteRegistration`.
    func deleteRegistrationPollingUntilDone(
      request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DomainsClient.retrieveAuthorizationCode`.
    func retrieveAuthorizationCode(
      request: RetrieveAuthorizationCodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.AuthorizationCode

    /// See `DomainsClient.resetAuthorizationCode`.
    func resetAuthorizationCode(
      request: ResetAuthorizationCodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.AuthorizationCode

    /// See `DomainsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.DomainsProtocol {
  public func searchDomains(request: SearchDomainsRequest) async throws
    -> GoogleCloudDomainsV1.SearchDomainsResponse
  {
    try await self.searchDomains(request: request, options: .init())
  }

  public func searchDomains(
    request: SearchDomainsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.SearchDomainsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchDomains(
    location: Swift.String,
    query: Swift.String,
  ) async throws -> GoogleCloudDomainsV1.SearchDomainsResponse {
    let request = SearchDomainsRequest().with {
      $0.location = location
      $0.query = query
    }
    return try await self.searchDomains(request: request)
  }

  public func retrieveRegisterParameters(request: RetrieveRegisterParametersRequest) async throws
    -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse
  {
    try await self.retrieveRegisterParameters(request: request, options: .init())
  }

  public func retrieveRegisterParameters(
    request: RetrieveRegisterParametersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func retrieveRegisterParameters(
    location: Swift.String,
    domainName: Swift.String,
  ) async throws -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse {
    let request = RetrieveRegisterParametersRequest().with {
      $0.location = location
      $0.domainName = domainName
    }
    return try await self.retrieveRegisterParameters(request: request)
  }

  public func registerDomain(request: RegisterDomainRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.registerDomain(request: request, options: .init())
  }

  public func registerDomain(
    request: RegisterDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func registerDomainPollingUntilDone(request: RegisterDomainRequest) async throws
    -> any GoogleGax.PollableOperation<Registration>
  {
    try await self.registerDomainPollingUntilDone(request: request, options: .init())
  }

  public func registerDomainPollingUntilDone(
    request: RegisterDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func registerDomainPollingUntilDone(
    parent: Swift.String,
    registration: Registration?,
    yearlyPrice: GoogleType.Money?,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = RegisterDomainRequest().with {
      $0.parent = parent
      $0.registration = registration
      $0.yearlyPrice = yearlyPrice
    }
    return try await self.registerDomainPollingUntilDone(request: request)
  }

  public func retrieveTransferParameters(request: RetrieveTransferParametersRequest) async throws
    -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse
  {
    try await self.retrieveTransferParameters(request: request, options: .init())
  }

  public func retrieveTransferParameters(
    request: RetrieveTransferParametersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func retrieveTransferParameters(
    location: Swift.String,
    domainName: Swift.String,
  ) async throws -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse {
    let request = RetrieveTransferParametersRequest().with {
      $0.location = location
      $0.domainName = domainName
    }
    return try await self.retrieveTransferParameters(request: request)
  }

  public func transferDomain(request: TransferDomainRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.transferDomain(request: request, options: .init())
  }

  public func transferDomain(
    request: TransferDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func transferDomainPollingUntilDone(request: TransferDomainRequest) async throws
    -> any GoogleGax.PollableOperation<Registration>
  {
    try await self.transferDomainPollingUntilDone(request: request, options: .init())
  }

  public func transferDomainPollingUntilDone(
    request: TransferDomainRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func transferDomainPollingUntilDone(
    parent: Swift.String,
    registration: Registration?,
    yearlyPrice: GoogleType.Money?,
    authorizationCode: AuthorizationCode?,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = TransferDomainRequest().with {
      $0.parent = parent
      $0.registration = registration
      $0.yearlyPrice = yearlyPrice
      $0.authorizationCode = authorizationCode
    }
    return try await self.transferDomainPollingUntilDone(request: request)
  }

  public func listRegistrations(request: ListRegistrationsRequest) async throws
    -> GoogleCloudDomainsV1.ListRegistrationsResponse
  {
    try await self.listRegistrations(request: request, options: .init())
  }

  public func listRegistrations(
    request: ListRegistrationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.ListRegistrationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRegistrationsByItems(
    request: ListRegistrationsRequest
  ) -> any AsyncSequence<Registration, Swift.Error> & Sendable {
    self.listRegistrationsByItems(request: request, options: .init())
  }

  /// Lists the `Registration` resources in a project.
  ///
  /// @Snippet(path: "Domains_ListRegistrations")
  public func listRegistrationsByItems(
    request: ListRegistrationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Registration, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudDomainsV1.ListRegistrationsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listRegistrations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRegistrationsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Registration, Swift.Error> & Sendable {
    let request = ListRegistrationsRequest().with {
      $0.parent = parent
    }
    return self.listRegistrationsByItems(request: request)
  }

  public func getRegistration(request: GetRegistrationRequest) async throws
    -> GoogleCloudDomainsV1.Registration
  {
    try await self.getRegistration(request: request, options: .init())
  }

  public func getRegistration(
    request: GetRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.Registration {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRegistration(
    name: Swift.String,
  ) async throws -> GoogleCloudDomainsV1.Registration {
    let request = GetRegistrationRequest().with {
      $0.name = name
    }
    return try await self.getRegistration(request: request)
  }

  public func updateRegistration(request: UpdateRegistrationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateRegistration(request: request, options: .init())
  }

  public func updateRegistration(
    request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateRegistrationPollingUntilDone(request: UpdateRegistrationRequest) async throws
    -> any GoogleGax.PollableOperation<Registration>
  {
    try await self.updateRegistrationPollingUntilDone(request: request, options: .init())
  }

  public func updateRegistrationPollingUntilDone(
    request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateRegistrationPollingUntilDone(
    registration: Registration?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = UpdateRegistrationRequest().with {
      $0.registration = registration
      $0.updateMask = updateMask
    }
    return try await self.updateRegistrationPollingUntilDone(request: request)
  }

  public func configureManagementSettings(request: ConfigureManagementSettingsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.configureManagementSettings(request: request, options: .init())
  }

  public func configureManagementSettings(
    request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func configureManagementSettingsPollingUntilDone(
    request: ConfigureManagementSettingsRequest
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    try await self.configureManagementSettingsPollingUntilDone(request: request, options: .init())
  }

  public func configureManagementSettingsPollingUntilDone(
    request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func configureManagementSettingsPollingUntilDone(
    registration: Swift.String,
    managementSettings: ManagementSettings?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = ConfigureManagementSettingsRequest().with {
      $0.registration = registration
      $0.managementSettings = managementSettings
      $0.updateMask = updateMask
    }
    return try await self.configureManagementSettingsPollingUntilDone(request: request)
  }

  public func configureDnsSettings(request: ConfigureDnsSettingsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.configureDnsSettings(request: request, options: .init())
  }

  public func configureDnsSettings(
    request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func configureDnsSettingsPollingUntilDone(request: ConfigureDnsSettingsRequest)
    async throws -> any GoogleGax.PollableOperation<Registration>
  {
    try await self.configureDnsSettingsPollingUntilDone(request: request, options: .init())
  }

  public func configureDnsSettingsPollingUntilDone(
    request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func configureDnsSettingsPollingUntilDone(
    registration: Swift.String,
    dnsSettings: DnsSettings?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = ConfigureDnsSettingsRequest().with {
      $0.registration = registration
      $0.dnsSettings = dnsSettings
      $0.updateMask = updateMask
    }
    return try await self.configureDnsSettingsPollingUntilDone(request: request)
  }

  public func configureContactSettings(request: ConfigureContactSettingsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.configureContactSettings(request: request, options: .init())
  }

  public func configureContactSettings(
    request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func configureContactSettingsPollingUntilDone(request: ConfigureContactSettingsRequest)
    async throws -> any GoogleGax.PollableOperation<Registration>
  {
    try await self.configureContactSettingsPollingUntilDone(request: request, options: .init())
  }

  public func configureContactSettingsPollingUntilDone(
    request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func configureContactSettingsPollingUntilDone(
    registration: Swift.String,
    contactSettings: ContactSettings?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = ConfigureContactSettingsRequest().with {
      $0.registration = registration
      $0.contactSettings = contactSettings
      $0.updateMask = updateMask
    }
    return try await self.configureContactSettingsPollingUntilDone(request: request)
  }

  public func exportRegistration(request: ExportRegistrationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.exportRegistration(request: request, options: .init())
  }

  public func exportRegistration(
    request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func exportRegistrationPollingUntilDone(request: ExportRegistrationRequest) async throws
    -> any GoogleGax.PollableOperation<Registration>
  {
    try await self.exportRegistrationPollingUntilDone(request: request, options: .init())
  }

  public func exportRegistrationPollingUntilDone(
    request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Registration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func exportRegistrationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Registration> {
    let request = ExportRegistrationRequest().with {
      $0.name = name
    }
    return try await self.exportRegistrationPollingUntilDone(request: request)
  }

  public func deleteRegistration(request: DeleteRegistrationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteRegistration(request: request, options: .init())
  }

  public func deleteRegistration(
    request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteRegistrationPollingUntilDone(request: DeleteRegistrationRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteRegistrationPollingUntilDone(request: request, options: .init())
  }

  public func deleteRegistrationPollingUntilDone(
    request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteRegistrationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteRegistrationRequest().with {
      $0.name = name
    }
    return try await self.deleteRegistrationPollingUntilDone(request: request)
  }

  public func retrieveAuthorizationCode(request: RetrieveAuthorizationCodeRequest) async throws
    -> GoogleCloudDomainsV1.AuthorizationCode
  {
    try await self.retrieveAuthorizationCode(request: request, options: .init())
  }

  public func retrieveAuthorizationCode(
    request: RetrieveAuthorizationCodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
    throw GoogleGax.RequestError.unimplemented
  }

  public func retrieveAuthorizationCode(
    registration: Swift.String,
  ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
    let request = RetrieveAuthorizationCodeRequest().with {
      $0.registration = registration
    }
    return try await self.retrieveAuthorizationCode(request: request)
  }

  public func resetAuthorizationCode(request: ResetAuthorizationCodeRequest) async throws
    -> GoogleCloudDomainsV1.AuthorizationCode
  {
    try await self.resetAuthorizationCode(request: request, options: .init())
  }

  public func resetAuthorizationCode(
    request: ResetAuthorizationCodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resetAuthorizationCode(
    registration: Swift.String,
  ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
    let request = ResetAuthorizationCodeRequest().with {
      $0.registration = registration
    }
    return try await self.resetAuthorizationCode(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Domains_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
