// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleType
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class DomainsRetry: DomainsStub {
    let inner: any DomainsStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any DomainsStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func searchDomains(
      request: SearchDomainsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.SearchDomainsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchDomainsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.SearchDomainsResponse
          in
          return try await self.inner.searchDomains(request: r, options: o)
        })
    }

    public func retrieveRegisterParameters(
      request: RetrieveRegisterParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: RetrieveRegisterParametersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse
          in
          return try await self.inner.retrieveRegisterParameters(request: r, options: o)
        })
    }

    public func registerDomain(
      request: RegisterDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RegisterDomainRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.registerDomain(request: r, options: o)
        })
    }

    public func retrieveTransferParameters(
      request: RetrieveTransferParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: RetrieveTransferParametersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse
          in
          return try await self.inner.retrieveTransferParameters(request: r, options: o)
        })
    }

    public func transferDomain(
      request: TransferDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: TransferDomainRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.transferDomain(request: r, options: o)
        })
    }

    public func listRegistrations(
      request: ListRegistrationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.ListRegistrationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListRegistrationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.ListRegistrationsResponse
          in
          return try await self.inner.listRegistrations(request: r, options: o)
        })
    }

    public func getRegistration(
      request: GetRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.Registration {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetRegistrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.Registration
          in
          return try await self.inner.getRegistration(request: r, options: o)
        })
    }

    public func updateRegistration(
      request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateRegistrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRegistration(request: r, options: o)
        })
    }

    public func configureManagementSettings(
      request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ConfigureManagementSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.configureManagementSettings(request: r, options: o)
        })
    }

    public func configureDnsSettings(
      request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ConfigureDnsSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.configureDnsSettings(request: r, options: o)
        })
    }

    public func configureContactSettings(
      request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ConfigureContactSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.configureContactSettings(request: r, options: o)
        })
    }

    public func exportRegistration(
      request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportRegistrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportRegistration(request: r, options: o)
        })
    }

    public func deleteRegistration(
      request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteRegistrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRegistration(request: r, options: o)
        })
    }

    public func retrieveAuthorizationCode(
      request: RetrieveAuthorizationCodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: RetrieveAuthorizationCodeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.AuthorizationCode
          in
          return try await self.inner.retrieveAuthorizationCode(request: r, options: o)
        })
    }

    public func resetAuthorizationCode(
      request: ResetAuthorizationCodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.AuthorizationCode {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResetAuthorizationCodeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDomainsV1.AuthorizationCode
          in
          return try await self.inner.resetAuthorizationCode(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
