// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `Registration` resource facilitates managing and configuring domain name
/// registrations.
///
/// There are several ways to create a new `Registration` resource:
///
/// To create a new `Registration` resource, find a suitable domain name by
/// calling the `SearchDomains` method with a query to see available domain name
/// options. After choosing a name, call `RetrieveRegisterParameters` to
/// ensure availability and obtain information like pricing, which is needed to
/// build a call to `RegisterDomain`.
///
/// Another way to create a new `Registration` is to transfer an existing
/// domain from another registrar. First, go to the current registrar to unlock
/// the domain for transfer and retrieve the domain's transfer authorization
/// code. Then call `RetrieveTransferParameters` to confirm that the domain is
/// unlocked and to get values needed to build a call to `TransferDomain`.
public struct Registration: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the `Registration` resource, in the format
  /// `projects/*/locations/*/registrations/<domain_name>`.
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The domain name. Unicode domain names must be expressed in Punycode format.
  public var domainName: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the `Registration` resource.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The expiration timestamp of the `Registration`.
  public var expireTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The state of the `Registration`
  public var state: Registration.State = Registration.State()

  /// Output only. The set of issues with the `Registration` that require attention.
  public var issues: [Registration.Issue] = []

  /// Set of labels associated with the `Registration`.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Settings for management of the `Registration`, including renewal, billing,
  /// and transfer. You cannot update these with the `UpdateRegistration`
  /// method. To update these settings, use the `ConfigureManagementSettings`
  /// method.
  public var managementSettings: ManagementSettings? = nil

  /// Settings controlling the DNS configuration of the `Registration`. You
  /// cannot update these with the `UpdateRegistration` method. To update these
  /// settings, use the `ConfigureDnsSettings` method.
  public var dnsSettings: DnsSettings? = nil

  /// Required. Settings for contact information linked to the `Registration`. You cannot
  /// update these with the `UpdateRegistration` method. To update these
  /// settings, use the `ConfigureContactSettings` method.
  public var contactSettings: ContactSettings? = nil

  /// Output only. Pending contact settings for the `Registration`. Updates to the
  /// `contact_settings` field that change its `registrant_contact` or `privacy`
  /// fields require email confirmation by the `registrant_contact`
  /// before taking effect. This field is set only if there are pending updates
  /// to the `contact_settings` that have not been confirmed. To confirm the
  /// changes, the `registrant_contact` must follow the instructions in the
  /// email they receive.
  public var pendingContactSettings: ContactSettings? = nil

  /// Output only. Set of options for the `contact_settings.privacy` field that this
  /// `Registration` supports.
  public var supportedPrivacy: [ContactPrivacy] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Registration`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Registration().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let domainName = CodingKeys(stringValue: "domainName")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let state = CodingKeys(stringValue: "state")
    static let issues = CodingKeys(stringValue: "issues")
    static let labels = CodingKeys(stringValue: "labels")
    static let managementSettings = CodingKeys(stringValue: "managementSettings")
    static let dnsSettings = CodingKeys(stringValue: "dnsSettings")
    static let contactSettings = CodingKeys(stringValue: "contactSettings")
    static let pendingContactSettings = CodingKeys(stringValue: "pendingContactSettings")
    static let supportedPrivacy = CodingKeys(stringValue: "supportedPrivacy")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "domainName",
      "createTime",
      "expireTime",
      "state",
      "issues",
      "labels",
      "managementSettings",
      "dnsSettings",
      "contactSettings",
      "pendingContactSettings",
      "supportedPrivacy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .domainName) {
      self.domainName = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.expireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(Registration.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent([Registration.Issue].self, forKey: .issues) {
      self.issues = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.managementSettings = try container.decodeIfPresent(
      ManagementSettings.self, forKey: .managementSettings)
    self.dnsSettings = try container.decodeIfPresent(DnsSettings.self, forKey: .dnsSettings)
    self.contactSettings = try container.decodeIfPresent(
      ContactSettings.self, forKey: .contactSettings)
    self.pendingContactSettings = try container.decodeIfPresent(
      ContactSettings.self, forKey: .pendingContactSettings)
    if let value = try container.decodeIfPresent([ContactPrivacy].self, forKey: .supportedPrivacy) {
      self.supportedPrivacy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.domainName, forKey: .domainName)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.issues, forKey: .issues)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.managementSettings, forKey: .managementSettings)
    try container.encodeIfPresent(self.dnsSettings, forKey: .dnsSettings)
    try container.encodeIfPresent(self.contactSettings, forKey: .contactSettings)
    try container.encodeIfPresent(self.pendingContactSettings, forKey: .pendingContactSettings)
    try container.encode(self.supportedPrivacy, forKey: .supportedPrivacy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible states of a `Registration`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The state is undefined.
    case unspecified
    /// The domain is being registered.
    case registrationPending
    /// The domain registration failed. You can delete resources in this state
    /// to allow registration to be retried.
    case registrationFailed
    /// The domain is being transferred from another registrar to Cloud Domains.
    case transferPending
    /// The attempt to transfer the domain from another registrar to
    /// Cloud Domains failed. You can delete resources in this state and retry
    /// the transfer.
    case transferFailed
    /// The domain is registered and operational. The domain renews automatically
    /// as long as it remains in this state.
    case active
    /// The domain is suspended and inoperative. For more details, see the
    /// `issues` field.
    case suspended
    /// The domain is no longer managed with Cloud Domains. It may have been
    /// transferred to another registrar or exported for management in
    /// [Google Domains](https://domains.google/). You can no longer update it
    /// with this API, and information shown about it may be stale. Domains in
    /// this state are not automatically renewed by Cloud Domains.
    case exported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .registrationPending: return 1
      case .registrationFailed: return 2
      case .transferPending: return 3
      case .transferFailed: return 4
      case .active: return 6
      case .suspended: return 7
      case .exported: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .registrationPending: return "REGISTRATION_PENDING"
      case .registrationFailed: return "REGISTRATION_FAILED"
      case .transferPending: return "TRANSFER_PENDING"
      case .transferFailed: return "TRANSFER_FAILED"
      case .active: return "ACTIVE"
      case .suspended: return "SUSPENDED"
      case .exported: return "EXPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "REGISTRATION_PENDING": self = .registrationPending
      case "REGISTRATION_FAILED": self = .registrationFailed
      case "TRANSFER_PENDING": self = .transferPending
      case "TRANSFER_FAILED": self = .transferFailed
      case "ACTIVE": self = .active
      case "SUSPENDED": self = .suspended
      case "EXPORTED": self = .exported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .registrationPending
      case 2: self = .registrationFailed
      case 3: self = .transferPending
      case 4: self = .transferFailed
      case 6: self = .active
      case 7: self = .suspended
      case 8: self = .exported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .registrationPending: return try container.encode("REGISTRATION_PENDING")
      case .registrationFailed: return try container.encode("REGISTRATION_FAILED")
      case .transferPending: return try container.encode("TRANSFER_PENDING")
      case .transferFailed: return try container.encode("TRANSFER_FAILED")
      case .active: return try container.encode("ACTIVE")
      case .suspended: return try container.encode("SUSPENDED")
      case .exported: return try container.encode("EXPORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible issues with a `Registration` that require attention.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Issue: Codable, Equatable, Hashable, Sendable {
    /// The issue is undefined.
    case unspecified
    /// Contact the Cloud Support team to resolve a problem with this domain.
    case contactSupport
    /// [ICANN](https://icann.org/) requires verification of the email address
    /// in the `Registration`'s `contact_settings.registrant_contact` field. To
    /// verify the email address, follow the
    /// instructions in the email the `registrant_contact` receives following
    /// registration. If you do not complete email verification within
    /// 15 days of registration, the domain is suspended. To resend the
    /// verification email, call ConfigureContactSettings and provide the current
    /// `registrant_contact.email`.
    case unverifiedEmail
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .contactSupport: return 1
      case .unverifiedEmail: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ISSUE_UNSPECIFIED"
      case .contactSupport: return "CONTACT_SUPPORT"
      case .unverifiedEmail: return "UNVERIFIED_EMAIL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Issue/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ISSUE_UNSPECIFIED": self = .unspecified
      case "CONTACT_SUPPORT": self = .contactSupport
      case "UNVERIFIED_EMAIL": self = .unverifiedEmail
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Issue/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .contactSupport
      case 2: self = .unverifiedEmail
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ISSUE_UNSPECIFIED")
      case .contactSupport: return try container.encode("CONTACT_SUPPORT")
      case .unverifiedEmail: return try container.encode("UNVERIFIED_EMAIL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.Registration"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
