// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for the `RegisterDomain` method.
public struct RegisterDomainRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent resource of the `Registration`. Must be in the
  /// format `projects/*/locations/*`.
  public var parent: Swift.String = Swift.String()

  /// Required. The complete `Registration` resource to be created.
  public var registration: Registration? = nil

  /// The list of domain notices that you acknowledge. Call
  /// `RetrieveRegisterParameters` to see the notices that need acknowledgement.
  public var domainNotices: [DomainNotice] = []

  /// The list of contact notices that the caller acknowledges. The notices
  /// needed here depend on the values specified in
  /// `registration.contact_settings`.
  public var contactNotices: [ContactNotice] = []

  /// Required. Yearly price to register or renew the domain.
  /// The value that should be put here can be obtained from
  /// RetrieveRegisterParameters or SearchDomains calls.
  public var yearlyPrice: GoogleType.Money? = nil

  /// When true, only validation is performed, without actually registering
  /// the domain. Follows:
  /// https://cloud.google.com/apis/design/design_patterns#request_validation
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RegisterDomainRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RegisterDomainRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let registration = CodingKeys(stringValue: "registration")
    static let domainNotices = CodingKeys(stringValue: "domainNotices")
    static let contactNotices = CodingKeys(stringValue: "contactNotices")
    static let yearlyPrice = CodingKeys(stringValue: "yearlyPrice")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "registration",
      "domainNotices",
      "contactNotices",
      "yearlyPrice",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.registration = try container.decodeIfPresent(Registration.self, forKey: .registration)
    if let value = try container.decodeIfPresent([DomainNotice].self, forKey: .domainNotices) {
      self.domainNotices = value
    }
    if let value = try container.decodeIfPresent([ContactNotice].self, forKey: .contactNotices) {
      self.contactNotices = value
    }
    self.yearlyPrice = try container.decodeIfPresent(GoogleType.Money.self, forKey: .yearlyPrice)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.registration, forKey: .registration)
    try container.encode(self.domainNotices, forKey: .domainNotices)
    try container.encode(self.contactNotices, forKey: .contactNotices)
    try container.encodeIfPresent(self.yearlyPrice, forKey: .yearlyPrice)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.RegisterDomainRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
