// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Parameters required to transfer a domain from another registrar.
public struct TransferParameters: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The domain name. Unicode domain names are expressed in Punycode format.
  public var domainName: Swift.String = Swift.String()

  /// The registrar that currently manages the domain.
  public var currentRegistrar: Swift.String = Swift.String()

  /// The name servers that currently store the configuration of the domain.
  public var nameServers: [Swift.String] = []

  /// Indicates whether the domain is protected by a transfer lock. For a
  /// transfer to succeed, this must show `UNLOCKED`. To unlock a domain,
  /// go to its current registrar.
  public var transferLockState: TransferLockState = TransferLockState()

  /// Contact privacy options that the domain supports.
  public var supportedPrivacy: [ContactPrivacy] = []

  /// Price to transfer or renew the domain for one year.
  public var yearlyPrice: GoogleType.Money? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferParameters().with { $0.domainName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let domainName = CodingKeys(stringValue: "domainName")
    static let currentRegistrar = CodingKeys(stringValue: "currentRegistrar")
    static let nameServers = CodingKeys(stringValue: "nameServers")
    static let transferLockState = CodingKeys(stringValue: "transferLockState")
    static let supportedPrivacy = CodingKeys(stringValue: "supportedPrivacy")
    static let yearlyPrice = CodingKeys(stringValue: "yearlyPrice")

    static let _knownKeys: Set<Swift.String> = [
      "domainName",
      "currentRegistrar",
      "nameServers",
      "transferLockState",
      "supportedPrivacy",
      "yearlyPrice",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .domainName) {
      self.domainName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currentRegistrar) {
      self.currentRegistrar = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .nameServers) {
      self.nameServers = value
    }
    if let value = try container.decodeIfPresent(TransferLockState.self, forKey: .transferLockState)
    {
      self.transferLockState = value
    }
    if let value = try container.decodeIfPresent([ContactPrivacy].self, forKey: .supportedPrivacy) {
      self.supportedPrivacy = value
    }
    self.yearlyPrice = try container.decodeIfPresent(GoogleType.Money.self, forKey: .yearlyPrice)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.domainName, forKey: .domainName)
    try container.encode(self.currentRegistrar, forKey: .currentRegistrar)
    try container.encode(self.nameServers, forKey: .nameServers)
    try container.encode(self.transferLockState, forKey: .transferLockState)
    try container.encode(self.supportedPrivacy, forKey: .supportedPrivacy)
    try container.encodeIfPresent(self.yearlyPrice, forKey: .yearlyPrice)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.TransferParameters"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
